// SynapStride v0.16 Stage 7B — child-side adaptive About Me presentation.
const BANDS=[{id:'early',min:5,max:7},{id:'middle',min:8,max:10},{id:'preteen',min:11,max:13},{id:'teen',min:14,max:18}]
export function getAboutMeAgeBand(age){const n=Number(age);return BANDS.find(b=>n>=b.min&&n<=b.max)?.id||'middle'}
function objective(q={}){const s=`${q.id||''} ${q.shortLabel||''} ${q.question||''}`.toLowerCase();if(/interest|enjoy|fun|favorite|curious/.test(s))return'interests';if(/learn|help|figure|understand|stuck/.test(s))return'learning_support';if(/challenge|motivat|excite|proud|keep going/.test(s))return'engagement';if(/try|explore|future|want/.test(s))return'exploration';return'self_expression'}
const COPY={
 early:{interests:['What looks fun to you?','Pick what feels fun today.'],learning_support:['What helps when something feels tricky?','Pick what helps you get going.'],engagement:['What makes you want to keep going?','Pick the one that sounds fun.'],exploration:['What would you like to try?','You can change your mind anytime.'],self_expression:['Which feels most like you?','There are no wrong picks.']},
 middle:{interests:['What have you been into lately?','Choose what sounds most like you today.'],learning_support:['How do you like figuring things out?','Choose what usually helps you get started.'],engagement:['What gets you interested?','Pick what tends to pull you in.'],exploration:['What would you like to explore more?','Curiosity counts — you do not have to be good at it yet.'],self_expression:['What sounds most like you?','Choose what feels closest today.']},
 preteen:{interests:['What are you into right now?','Pick what you actually enjoy spending time on.'],learning_support:['When something is new, what helps you get it?','Pick what tends to work best for you.'],engagement:['What makes something worth sticking with?','Choose what usually keeps your attention.'],exploration:['What are you curious enough to try?','This can be something completely new.'],self_expression:['Which sounds most like you lately?','This is a clue, not a permanent label.']},
 teen:{interests:['What has your attention lately?','Choose what you genuinely want to spend time exploring.'],learning_support:['What kind of support actually helps?','Pick what tends to move you forward.'],engagement:['What keeps you engaged?','Choose what most often makes something feel worth doing.'],exploration:['What do you want to explore next?','It is fine if this changes over time.'],self_expression:['What feels most like you right now?','Treat this as a current signal, not a label.']}
}
export function buildAboutMeExperiencePlan({childProfile={},questions=[]}={}){const ageBand=getAboutMeAgeBand(childProfile.age);return questions.map((q,index)=>{const o=objective(q),[adaptivePrompt,adaptiveHint]=COPY[ageBand][o]||COPY[ageBand].self_expression;return{...q,originalQuestion:q.question,objective:o,ageBand,adaptivePrompt,adaptiveHint,sequence:index+1,evidenceMode:'child_explicit'}})}
export function validateAboutMeModelPlan(modelPlan,approvedQuestions=[]){if(!modelPlan||!Array.isArray(modelPlan.interactions))return null;const approved=new Map(approvedQuestions.map(q=>[q.id,q]));const interactions=modelPlan.interactions.map(item=>{const source=approved.get(item.questionId);if(!source)return null;const allowed=new Set((source.answers||[]).map(a=>a.id));const answerIds=Array.isArray(item.answerIds)?item.answerIds.filter(id=>allowed.has(id)):(source.answers||[]).map(a=>a.id);if(!answerIds.length)return null;return{questionId:source.id,answerIds,prompt:String(item.prompt||'').slice(0,180),hint:String(item.hint||'').slice(0,180)}}).filter(Boolean);return interactions.length?{interactions}:null}

export function buildAboutMePlanningContext({childProfile={},profileUnderstanding=null}={}){
 const state=profileUnderstanding?.stated?.aboutMeEvidenceState||{}
 return {ageBand:getAboutMeAgeBand(childProfile.age),answeredQuestionIds:Array.isArray(state.answeredQuestionIds)?state.answeredQuestionIds:[],currentExplicitAnswerCount:Number(state.currentExplicitAnswerCount||0),instruction:'Prefer useful unanswered objectives; ask for confirmation only when a current child-stated signal may have changed.'}
}
