import { useMemo, useState } from 'react'
import { buildAboutMeExperiencePlan } from '../intelligence/aboutMeExperiencePlanner'
import './DiscoverExperienceV015.css'
const icons=['✨','🚀','🎨','🧪','🛠️','🐾','🎮','🌱']
function visual(label='',i=0){const m=String(label).match(/^(\p{Extended_Pictographic}(?:\uFE0F|\u200D\p{Extended_Pictographic})*)\s*(.*)$/u);return{emoji:m?.[1]||icons[i%icons.length],text:m?.[2]||label}}
export default function DiscoveryFlow({childProfile,questions,currentQuestionIndex,currentQuestion,onBack,onAnswer}){
 const[started,setStarted]=useState(false),[selectedId,setSelectedId]=useState(null)
 const plan=useMemo(()=>buildAboutMeExperiencePlan({childProfile,questions}),[childProfile,questions])
 const planned=plan[currentQuestionIndex]||currentQuestion;if(!planned||!questions?.length)return null
 const name=childProfile?.name?.trim()||'Explorer',n=currentQuestionIndex+1,pct=n/questions.length*100
 const answers=(planned.answers||[]).map((a,i)=>({...a,...visual(a.label,i)}))
 const choose=a=>{setSelectedId(a.id);window.setTimeout(()=>{setSelectedId(null);onAnswer(a)},180)}
 if(!started&&currentQuestionIndex===0)return <section className="ss-about-v016"><div className="ss-about-v016__welcome"><div className="ss-about-v016__welcomeCopy"><span className="ss-about-v016__eyebrow">✨ ABOUT ME</span><h1>Hi {name}! 👋<br/>Let’s figure out what makes you, you.</h1><p>This is not a test. Pick what feels like you today. As you learn, try things and grow, I’ll keep learning with you.</p><div className="ss-about-v016__trail"><span><b>❤️</b> Things you’re into</span><span><b>🧠</b> What helps you figure things out</span><span><b>🚀</b> Things you want to explore</span></div><button type="button" className="ss-about-v016__primary" onClick={()=>setStarted(true)}>Let’s get started! →</button><small>You can change your mind later. These are clues, not labels.</small></div><div className="ss-about-v016__welcomeArt" aria-hidden="true"><div className="ss-about-v016__planet">🪐</div><div className="ss-about-v016__kid">🧒</div><div className="ss-about-v016__buddy">🤖</div><div className="ss-about-v016__signs"><span>EXPLORE</span><span>TRY THINGS</span><span>GROW</span></div></div></div></section>
 return <section className="ss-about-v016"><div className="ss-about-v016__questionShell"><header className="ss-about-v016__questionTop"><button type="button" className="ss-about-v016__back" onClick={currentQuestionIndex===0?()=>setStarted(false):onBack}>← Back</button><div className="ss-about-v016__progress"><div><i style={{width:`${pct}%`}}/></div><span>{n} of {questions.length}</span></div><span className="ss-about-v016__mini">✨ About Me</span></header><div className="ss-about-v016__prompt"><span>{planned.objective?.replace('_',' ')||planned.shortLabel||'About you'}</span><h1>{planned.adaptivePrompt||planned.question}</h1><p>{planned.adaptiveHint||'Choose what feels most like you today.'}</p></div><div className="ss-about-v016__visualAnswers">{answers.map(a=><button type="button" key={a.id} className={selectedId===a.id?'selected':''} onClick={()=>choose(a)}><b>{a.emoji}</b><strong>{a.text}</strong>{selectedId===a.id&&<em>✓</em>}</button>)}</div><div className="ss-about-v016__inlineAck"><span>🤖</span><p><strong>Every answer is one clue.</strong> I’ll combine what you tell me with what you actually try inside SynapStride.</p></div></div></section>
}
